# Generated by Django 2.2 on 2020-06-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='flower_image',
            field=models.ImageField(blank=True, upload_to='flower_images'),
        ),
    ]
